// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209202853_Innitial")]
    partial class Innitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DetectedTools.DetectedTool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("PhotoSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_session_id");

                    b.Property<bool>("RedFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("red_flagged");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("ToolAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_assignment_id");

                    b.Property<Guid>("ToolTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_type_id");

                    b.HasKey("Id")
                        .HasName("pk_detected_tools");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_detected_tools_brand_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_detected_tools_model_id");

                    b.HasIndex("PhotoSessionId")
                        .HasDatabaseName("ix_detected_tools_photo_session_id");

                    b.HasIndex("ToolAssignmentId")
                        .HasDatabaseName("ix_detected_tools_tool_assignment_id");

                    b.HasIndex("ToolTypeId")
                        .HasDatabaseName("ix_detected_tools_tool_type_id");

                    b.ToTable("detected_tools", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Guid>("LocationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_type_id");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("LocationTypeId")
                        .HasDatabaseName("ix_locations_location_type_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Locations.LocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_location_types");

                    b.ToTable("location_types", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.ActionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_action_types");

                    b.ToTable("action_types", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.PhotoForDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("original_name");

                    b.Property<Guid>("PhotoSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_session_id");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id")
                        .HasName("pk_photos_for_detection");

                    b.HasIndex("PhotoSessionId")
                        .HasDatabaseName("ix_photos_for_detection_photo_session_id");

                    b.ToTable("photos_for_detection", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.PhotoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Id")
                        .HasName("pk_photo_sessions");

                    b.HasIndex("ActionTypeId")
                        .HasDatabaseName("ix_photo_sessions_action_type_id");

                    b.ToTable("photo_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolAssignments.ToolAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ReturnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("ReturnedDetectedToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_detected_tool_id");

                    b.Property<Guid?>("ReturnedLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_location_id");

                    b.Property<DateTime>("TakenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("TakenDetectedToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("taken_detected_tool_id");

                    b.Property<Guid>("TakenLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("taken_location_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tool_assignments");

                    b.HasIndex("ReturnedDetectedToolId")
                        .HasDatabaseName("ix_tool_assignments_returned_detected_tool_id");

                    b.HasIndex("ReturnedLocationId")
                        .HasDatabaseName("ix_tool_assignments_returned_location_id");

                    b.HasIndex("TakenDetectedToolId")
                        .HasDatabaseName("ix_tool_assignments_taken_detected_tool_id");

                    b.HasIndex("TakenLocationId")
                        .HasDatabaseName("ix_tool_assignments_taken_location_id");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("ix_tool_assignments_tool_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tool_assignments_user_id");

                    b.ToTable("tool_assignments", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.ToolStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tool_statuses");

                    b.ToTable("tool_statuses", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.ToolType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tool_types");

                    b.ToTable("tool_types", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolPhotos.PhotoType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_photo_types");

                    b.ToTable("photo_types", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ToolPhotos.ToolPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("original_name");

                    b.Property<Guid>("PhotoTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_type_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id")
                        .HasName("pk_tool_photos");

                    b.HasIndex("PhotoTypeId")
                        .HasDatabaseName("ix_tool_photos_photo_type_id");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("ix_tool_photos_tool_id");

                    b.ToTable("tool_photos", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Tools.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("ToolStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_status_id");

                    b.Property<Guid>("ToolTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_type_id");

                    b.HasKey("Id")
                        .HasName("pk_tools");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_tools_brand_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_tools_model_id");

                    b.HasIndex("ToolStatusId")
                        .HasDatabaseName("ix_tools_tool_status_id");

                    b.HasIndex("ToolTypeId")
                        .HasDatabaseName("ix_tools_tool_type_id");

                    b.ToTable("tools", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConfirmedEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DetectedTools.DetectedTool", b =>
                {
                    b.HasOne("Domain.Models.ToolInfo.Brand", "Brand")
                        .WithMany("DetectedTools")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_detected_tools_brands_brand_id");

                    b.HasOne("Domain.Models.ToolInfo.Model", "Model")
                        .WithMany("DetectedTools")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_detected_tools_models_model_id");

                    b.HasOne("Domain.Models.PhotoSessions.PhotoSession", "PhotoSession")
                        .WithMany("DetectedTools")
                        .HasForeignKey("PhotoSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detected_tools_photo_sessions_photo_session_id");

                    b.HasOne("Domain.Models.ToolAssignments.ToolAssignment", "ToolAssignment")
                        .WithMany()
                        .HasForeignKey("ToolAssignmentId")
                        .HasConstraintName("fk_detected_tools_tool_assignments_tool_assignment_id");

                    b.HasOne("Domain.Models.ToolInfo.ToolType", "ToolType")
                        .WithMany("DetectedTools")
                        .HasForeignKey("ToolTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detected_tools_tool_types_tool_type_id");

                    b.Navigation("Brand");

                    b.Navigation("Model");

                    b.Navigation("PhotoSession");

                    b.Navigation("ToolAssignment");

                    b.Navigation("ToolType");
                });

            modelBuilder.Entity("Domain.Models.Locations.Location", b =>
                {
                    b.HasOne("Domain.Models.Locations.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_location_types_location_type_id");

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.PhotoForDetection", b =>
                {
                    b.HasOne("Domain.Models.PhotoSessions.PhotoSession", "PhotoSession")
                        .WithMany("PhotosForDetection")
                        .HasForeignKey("PhotoSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photos_for_detection_photo_sessions_photo_session_id");

                    b.Navigation("PhotoSession");
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.PhotoSession", b =>
                {
                    b.HasOne("Domain.Models.PhotoSessions.ActionType", "ActionType")
                        .WithMany("PhotoSessions")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photo_sessions_action_types_action_type_id");

                    b.Navigation("ActionType");
                });

            modelBuilder.Entity("Domain.Models.ToolAssignments.ToolAssignment", b =>
                {
                    b.HasOne("Domain.Models.DetectedTools.DetectedTool", "ReturnedDetectedTool")
                        .WithMany()
                        .HasForeignKey("ReturnedDetectedToolId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tool_assignments_detected_tools_returned_detected_tool_id");

                    b.HasOne("Domain.Models.Locations.Location", "ReturnedLocation")
                        .WithMany()
                        .HasForeignKey("ReturnedLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tool_assignments_locations_returned_location_id");

                    b.HasOne("Domain.Models.DetectedTools.DetectedTool", "TakenDetectedTool")
                        .WithMany()
                        .HasForeignKey("TakenDetectedToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_assignments_detected_tools_taken_detected_tool_id");

                    b.HasOne("Domain.Models.Locations.Location", "TakenLocation")
                        .WithMany("ToolAssignments")
                        .HasForeignKey("TakenLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_assignments_locations_taken_location_id");

                    b.HasOne("Domain.Models.Tools.Tool", "Tool")
                        .WithMany("ToolAssignments")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_assignments_tools_tool_id");

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("ToolAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_assignments_users_user_id");

                    b.Navigation("ReturnedDetectedTool");

                    b.Navigation("ReturnedLocation");

                    b.Navigation("TakenDetectedTool");

                    b.Navigation("TakenLocation");

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ToolPhotos.ToolPhoto", b =>
                {
                    b.HasOne("Domain.Models.ToolPhotos.PhotoType", "PhotoType")
                        .WithMany("ToolPhotos")
                        .HasForeignKey("PhotoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_photos_photo_types_photo_type_id");

                    b.HasOne("Domain.Models.Tools.Tool", "Tool")
                        .WithMany("ToolPhotos")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_photos_tools_tool_id");

                    b.Navigation("PhotoType");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Domain.Models.Tools.Tool", b =>
                {
                    b.HasOne("Domain.Models.ToolInfo.Brand", "Brand")
                        .WithMany("Tools")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tools_brands_brand_id");

                    b.HasOne("Domain.Models.ToolInfo.Model", "Model")
                        .WithMany("Tools")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tools_models_model_id");

                    b.HasOne("Domain.Models.ToolInfo.ToolStatus", "ToolStatus")
                        .WithMany("Tools")
                        .HasForeignKey("ToolStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tools_tool_statuses_tool_status_id");

                    b.HasOne("Domain.Models.ToolInfo.ToolType", "ToolType")
                        .WithMany("Tools")
                        .HasForeignKey("ToolTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tools_tool_types_tool_type_id");

                    b.Navigation("Brand");

                    b.Navigation("Model");

                    b.Navigation("ToolStatus");

                    b.Navigation("ToolType");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.HasOne("Domain.Models.Roles.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Models.Locations.Location", b =>
                {
                    b.Navigation("ToolAssignments");
                });

            modelBuilder.Entity("Domain.Models.Locations.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.ActionType", b =>
                {
                    b.Navigation("PhotoSessions");
                });

            modelBuilder.Entity("Domain.Models.PhotoSessions.PhotoSession", b =>
                {
                    b.Navigation("DetectedTools");

                    b.Navigation("PhotosForDetection");
                });

            modelBuilder.Entity("Domain.Models.Roles.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.Brand", b =>
                {
                    b.Navigation("DetectedTools");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.Model", b =>
                {
                    b.Navigation("DetectedTools");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.ToolStatus", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Domain.Models.ToolInfo.ToolType", b =>
                {
                    b.Navigation("DetectedTools");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Domain.Models.ToolPhotos.PhotoType", b =>
                {
                    b.Navigation("ToolPhotos");
                });

            modelBuilder.Entity("Domain.Models.Tools.Tool", b =>
                {
                    b.Navigation("ToolAssignments");

                    b.Navigation("ToolPhotos");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Navigation("ToolAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
